import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { Providers } from "./providers";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import { SearchCommandMenu } from "@/modules/search/search-command-menu";
import { Suspense } from "react";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} bg-black antialiased`}>
        <Providers>
          <ThemeProvider forcedTheme="dark" attribute="class">
            <Suspense fallback={null}>
              <SearchCommandMenu />
            </Suspense>
            {children}
          </ThemeProvider>
        </Providers>
        <Toaster theme="dark" position="bottom-center" richColors />
        <Analytics />
      </body>
    </html>
  );
}
